input_paths:
  abstracts: "../data/abstract-20250508.json"
  reviewers: "../data/referees-20250508-v2 copy.json"

output_paths:
  abstract_reviewers: "../outputs/abstract_reviewers.json"
  reviewers_assignment: "../outputs/reviewers_assignment.json"

cache_paths:
  authors: "../cache/cached_authors.json"
  reviewers: "../cache/cached_reviewers.json"
  coauth_graph: "../cache/coauth_graph.pkl"

parameters:
  max_assign: 5 # numero di assegnazioni massime per un revisore standard
  max_assign_jolly: 7 # numero di assegnazioni massime per un revisore jolly
  required_reviewers:
    "Oral communication": 3 # numero di revisori necessari per Oral communication
    "Poster": 1 # numero di revisori necessari per Poster
    "Late Poster": 1 # numero di revisori necessari per Late Poster
    
    
  jolly_revs:
    - '7004035394' # Raffaele Calogero
    - '12770864300' # Pasqualina D'Ursi
    - '6603766091' # Mario Cannataro
    - '6603748349' # Manuela Helmer Citterich
    - '35965781000' # Claudia Angelini
    - '35565731300' # Maria Luisa Chiusano
    - '7006342790' # Angelo Facchiano
    - '6603693872' # Paola Festa
    - '57215730807' # Bruno Hay Mele
    - '6602147686' # Anna Marabotti
    - '7004695643' # Roberto Tagliaferri
    - '57015392700' # Francesco Bardozzo

    - '55919285100' # Matteo Pallocca
    - '23488108200' # Alessandro Cestaro
